site_name: Barbucket
site_url: https://github.com/croidzen/barbucket
repo_name: croidzen/barbucket
repo_url: https://github.com/croidzen/barbucket

nav:
  - Overview: 'index.md'
  - Quickstart: 'quickstart.md'
  - Installation: 'installation.md'
  - Configuration: 'config.md'
  - CLI: 'cli.md'
  - Database: 'database.md'
  - Contracts:
    - Syncronize contracts: 'sync_contracts.md'
    - IB contract details: 'ib_contract_details.md'
    - TV screener: 'tv_screener.md'
  - Universes: 'universes.md'
  - Quotes: 'quotes.md'

# mkdocs-material configuration
theme:
  name: material
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    - scheme: slate 
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking

  icon:
    repo: fontawesome/brands/github